# Generated by Django 4.0 on 2021-07-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_see_all_borrowed', 'Display all borrowed books'),)},
        ),
    ]
